// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/orchestrator/orchestrator.proto

package orchestrator

import (
	metrics "github.com/vermakmanish001/go_sentinel/proto/metrics"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestStatusResponse_Status int32

const (
	TestStatusResponse_UNKNOWN   TestStatusResponse_Status = 0
	TestStatusResponse_PENDING   TestStatusResponse_Status = 1
	TestStatusResponse_RUNNING   TestStatusResponse_Status = 2
	TestStatusResponse_COMPLETED TestStatusResponse_Status = 3
	TestStatusResponse_FAILED    TestStatusResponse_Status = 4
	TestStatusResponse_STOPPED   TestStatusResponse_Status = 5
)

// Enum value maps for TestStatusResponse_Status.
var (
	TestStatusResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "PENDING",
		2: "RUNNING",
		3: "COMPLETED",
		4: "FAILED",
		5: "STOPPED",
	}
	TestStatusResponse_Status_value = map[string]int32{
		"UNKNOWN":   0,
		"PENDING":   1,
		"RUNNING":   2,
		"COMPLETED": 3,
		"FAILED":    4,
		"STOPPED":   5,
	}
)

func (x TestStatusResponse_Status) Enum() *TestStatusResponse_Status {
	p := new(TestStatusResponse_Status)
	*p = x
	return p
}

func (x TestStatusResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestStatusResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_orchestrator_orchestrator_proto_enumTypes[0].Descriptor()
}

func (TestStatusResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_orchestrator_orchestrator_proto_enumTypes[0]
}

func (x TestStatusResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestStatusResponse_Status.Descriptor instead.
func (TestStatusResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{15, 0}
}

// Test plan definition
type TestPlan struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Stages            []*Stage               `protobuf:"bytes,3,rep,name=stages,proto3" json:"stages,omitempty"`
	Http              *HTTPConfig            `protobuf:"bytes,4,opt,name=http,proto3" json:"http,omitempty"`
	Variables         map[string]string      `protobuf:"bytes,5,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TotalVirtualUsers int32                  `protobuf:"varint,6,opt,name=total_virtual_users,json=totalVirtualUsers,proto3" json:"total_virtual_users,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TestPlan) Reset() {
	*x = TestPlan{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestPlan) ProtoMessage() {}

func (x *TestPlan) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestPlan.ProtoReflect.Descriptor instead.
func (*TestPlan) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *TestPlan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestPlan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestPlan) GetStages() []*Stage {
	if x != nil {
		return x.Stages
	}
	return nil
}

func (x *TestPlan) GetHttp() *HTTPConfig {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *TestPlan) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *TestPlan) GetTotalVirtualUsers() int32 {
	if x != nil {
		return x.TotalVirtualUsers
	}
	return 0
}

// Load test stage
type Stage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Duration      string                 `protobuf:"bytes,1,opt,name=duration,proto3" json:"duration,omitempty"` // e.g., "30s", "1m"
	TargetVus     int32                  `protobuf:"varint,2,opt,name=target_vus,json=targetVus,proto3" json:"target_vus,omitempty"`
	RampUp        string                 `protobuf:"bytes,3,opt,name=ramp_up,json=rampUp,proto3" json:"ramp_up,omitempty"` // optional, e.g., "5s"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stage) Reset() {
	*x = Stage{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stage) ProtoMessage() {}

func (x *Stage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stage.ProtoReflect.Descriptor instead.
func (*Stage) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *Stage) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *Stage) GetTargetVus() int32 {
	if x != nil {
		return x.TargetVus
	}
	return 0
}

func (x *Stage) GetRampUp() string {
	if x != nil {
		return x.RampUp
	}
	return ""
}

// HTTP configuration
type HTTPConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseUrl       string                 `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Requests      []*Request             `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutMs     int32                  `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPConfig) Reset() {
	*x = HTTPConfig{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPConfig) ProtoMessage() {}

func (x *HTTPConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPConfig.ProtoReflect.Descriptor instead.
func (*HTTPConfig) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *HTTPConfig) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *HTTPConfig) GetRequests() []*Request {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *HTTPConfig) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPConfig) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// HTTP request definition
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"` // GET, POST, PUT, DELETE, etc.
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Assertions    []*Assertion           `protobuf:"bytes,5,rep,name=assertions,proto3" json:"assertions,omitempty"`
	ThinkTimeMs   int32                  `protobuf:"varint,6,opt,name=think_time_ms,json=thinkTimeMs,proto3" json:"think_time_ms,omitempty"` // time to wait after request
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *Request) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Request) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Request) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Request) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Request) GetAssertions() []*Assertion {
	if x != nil {
		return x.Assertions
	}
	return nil
}

func (x *Request) GetThinkTimeMs() int32 {
	if x != nil {
		return x.ThinkTimeMs
	}
	return 0
}

// Response assertion
type Assertion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Assertion:
	//
	//	*Assertion_StatusCode
	//	*Assertion_ResponseTime
	//	*Assertion_BodyContains
	Assertion     isAssertion_Assertion `protobuf_oneof:"assertion"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assertion) Reset() {
	*x = Assertion{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assertion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assertion) ProtoMessage() {}

func (x *Assertion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assertion.ProtoReflect.Descriptor instead.
func (*Assertion) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *Assertion) GetAssertion() isAssertion_Assertion {
	if x != nil {
		return x.Assertion
	}
	return nil
}

func (x *Assertion) GetStatusCode() *StatusCodeAssertion {
	if x != nil {
		if x, ok := x.Assertion.(*Assertion_StatusCode); ok {
			return x.StatusCode
		}
	}
	return nil
}

func (x *Assertion) GetResponseTime() *ResponseTimeAssertion {
	if x != nil {
		if x, ok := x.Assertion.(*Assertion_ResponseTime); ok {
			return x.ResponseTime
		}
	}
	return nil
}

func (x *Assertion) GetBodyContains() *BodyContainsAssertion {
	if x != nil {
		if x, ok := x.Assertion.(*Assertion_BodyContains); ok {
			return x.BodyContains
		}
	}
	return nil
}

type isAssertion_Assertion interface {
	isAssertion_Assertion()
}

type Assertion_StatusCode struct {
	StatusCode *StatusCodeAssertion `protobuf:"bytes,1,opt,name=status_code,json=statusCode,proto3,oneof"`
}

type Assertion_ResponseTime struct {
	ResponseTime *ResponseTimeAssertion `protobuf:"bytes,2,opt,name=response_time,json=responseTime,proto3,oneof"`
}

type Assertion_BodyContains struct {
	BodyContains *BodyContainsAssertion `protobuf:"bytes,3,opt,name=body_contains,json=bodyContains,proto3,oneof"`
}

func (*Assertion_StatusCode) isAssertion_Assertion() {}

func (*Assertion_ResponseTime) isAssertion_Assertion() {}

func (*Assertion_BodyContains) isAssertion_Assertion() {}

type StatusCodeAssertion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expected      int32                  `protobuf:"varint,1,opt,name=expected,proto3" json:"expected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusCodeAssertion) Reset() {
	*x = StatusCodeAssertion{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusCodeAssertion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusCodeAssertion) ProtoMessage() {}

func (x *StatusCodeAssertion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusCodeAssertion.ProtoReflect.Descriptor instead.
func (*StatusCodeAssertion) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *StatusCodeAssertion) GetExpected() int32 {
	if x != nil {
		return x.Expected
	}
	return 0
}

type ResponseTimeAssertion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Percentile    string                 `protobuf:"bytes,1,opt,name=percentile,proto3" json:"percentile,omitempty"` // P50, P95, P99
	MaxMs         int32                  `protobuf:"varint,2,opt,name=max_ms,json=maxMs,proto3" json:"max_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseTimeAssertion) Reset() {
	*x = ResponseTimeAssertion{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseTimeAssertion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseTimeAssertion) ProtoMessage() {}

func (x *ResponseTimeAssertion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseTimeAssertion.ProtoReflect.Descriptor instead.
func (*ResponseTimeAssertion) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *ResponseTimeAssertion) GetPercentile() string {
	if x != nil {
		return x.Percentile
	}
	return ""
}

func (x *ResponseTimeAssertion) GetMaxMs() int32 {
	if x != nil {
		return x.MaxMs
	}
	return 0
}

type BodyContainsAssertion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Substring     string                 `protobuf:"bytes,1,opt,name=substring,proto3" json:"substring,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BodyContainsAssertion) Reset() {
	*x = BodyContainsAssertion{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BodyContainsAssertion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodyContainsAssertion) ProtoMessage() {}

func (x *BodyContainsAssertion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodyContainsAssertion.ProtoReflect.Descriptor instead.
func (*BodyContainsAssertion) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *BodyContainsAssertion) GetSubstring() string {
	if x != nil {
		return x.Substring
	}
	return ""
}

// Distribute test plan request
type DistributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plan          *TestPlan              `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistributeRequest) Reset() {
	*x = DistributeRequest{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributeRequest) ProtoMessage() {}

func (x *DistributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistributeRequest.ProtoReflect.Descriptor instead.
func (*DistributeRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{8}
}

func (x *DistributeRequest) GetPlan() *TestPlan {
	if x != nil {
		return x.Plan
	}
	return nil
}

// Distribute test plan response
type DistributeResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TestId               string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	WorkersAssigned      int32                  `protobuf:"varint,2,opt,name=workers_assigned,json=workersAssigned,proto3" json:"workers_assigned,omitempty"`
	WorkerVuDistribution map[string]int32       `protobuf:"bytes,3,rep,name=worker_vu_distribution,json=workerVuDistribution,proto3" json:"worker_vu_distribution,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // worker_id -> virtual_users
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DistributeResponse) Reset() {
	*x = DistributeResponse{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistributeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributeResponse) ProtoMessage() {}

func (x *DistributeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistributeResponse.ProtoReflect.Descriptor instead.
func (*DistributeResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{9}
}

func (x *DistributeResponse) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *DistributeResponse) GetWorkersAssigned() int32 {
	if x != nil {
		return x.WorkersAssigned
	}
	return 0
}

func (x *DistributeResponse) GetWorkerVuDistribution() map[string]int32 {
	if x != nil {
		return x.WorkerVuDistribution
	}
	return nil
}

// Stream metrics request
type StreamMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMetricsRequest) Reset() {
	*x = StreamMetricsRequest{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMetricsRequest) ProtoMessage() {}

func (x *StreamMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMetricsRequest.ProtoReflect.Descriptor instead.
func (*StreamMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{10}
}

func (x *StreamMetricsRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

// Stream metrics response
type StreamMetricsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Snapshot      *metrics.MetricSnapshot `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	TimestampMs   int64                   `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMetricsResponse) Reset() {
	*x = StreamMetricsResponse{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMetricsResponse) ProtoMessage() {}

func (x *StreamMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMetricsResponse.ProtoReflect.Descriptor instead.
func (*StreamMetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{11}
}

func (x *StreamMetricsResponse) GetSnapshot() *metrics.MetricSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *StreamMetricsResponse) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

// Register worker request
type RegisterWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	MaxVus        int32                  `protobuf:"varint,3,opt,name=max_vus,json=maxVus,proto3" json:"max_vus,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterWorkerRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterWorkerRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterWorkerRequest) GetMaxVus() int32 {
	if x != nil {
		return x.MaxVus
	}
	return 0
}

func (x *RegisterWorkerRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Register worker response
type RegisterWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerResponse) Reset() {
	*x = RegisterWorkerResponse{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerResponse) ProtoMessage() {}

func (x *RegisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterWorkerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterWorkerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Test status request
type TestStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestStatusRequest) Reset() {
	*x = TestStatusRequest{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestStatusRequest) ProtoMessage() {}

func (x *TestStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestStatusRequest.ProtoReflect.Descriptor instead.
func (*TestStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{14}
}

func (x *TestStatusRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

// Test status response
type TestStatusResponse struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	Status         TestStatusResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=orchestrator.TestStatusResponse_Status" json:"status,omitempty"`
	ActiveWorkers  int32                     `protobuf:"varint,2,opt,name=active_workers,json=activeWorkers,proto3" json:"active_workers,omitempty"`
	TotalVus       int32                     `protobuf:"varint,3,opt,name=total_vus,json=totalVus,proto3" json:"total_vus,omitempty"`
	CurrentMetrics *metrics.MetricSnapshot   `protobuf:"bytes,4,opt,name=current_metrics,json=currentMetrics,proto3" json:"current_metrics,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TestStatusResponse) Reset() {
	*x = TestStatusResponse{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestStatusResponse) ProtoMessage() {}

func (x *TestStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestStatusResponse.ProtoReflect.Descriptor instead.
func (*TestStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{15}
}

func (x *TestStatusResponse) GetStatus() TestStatusResponse_Status {
	if x != nil {
		return x.Status
	}
	return TestStatusResponse_UNKNOWN
}

func (x *TestStatusResponse) GetActiveWorkers() int32 {
	if x != nil {
		return x.ActiveWorkers
	}
	return 0
}

func (x *TestStatusResponse) GetTotalVus() int32 {
	if x != nil {
		return x.TotalVus
	}
	return 0
}

func (x *TestStatusResponse) GetCurrentMetrics() *metrics.MetricSnapshot {
	if x != nil {
		return x.CurrentMetrics
	}
	return nil
}

// Stop test request
type StopTestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTestRequest) Reset() {
	*x = StopTestRequest{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTestRequest) ProtoMessage() {}

func (x *StopTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTestRequest.ProtoReflect.Descriptor instead.
func (*StopTestRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{16}
}

func (x *StopTestRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

// Stop test response
type StopTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTestResponse) Reset() {
	*x = StopTestResponse{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTestResponse) ProtoMessage() {}

func (x *StopTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTestResponse.ProtoReflect.Descriptor instead.
func (*StopTestResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{17}
}

func (x *StopTestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopTestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ReportMetrics response
type ReportMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportMetricsResponse) Reset() {
	*x = ReportMetricsResponse{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportMetricsResponse) ProtoMessage() {}

func (x *ReportMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportMetricsResponse.ProtoReflect.Descriptor instead.
func (*ReportMetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{18}
}

func (x *ReportMetricsResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

// ListWorkers request
type ListWorkersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkersRequest) Reset() {
	*x = ListWorkersRequest{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkersRequest) ProtoMessage() {}

func (x *ListWorkersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkersRequest.ProtoReflect.Descriptor instead.
func (*ListWorkersRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{19}
}

// ListWorkers response
type ListWorkersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workers       []*WorkerInfo          `protobuf:"bytes,1,rep,name=workers,proto3" json:"workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkersResponse) Reset() {
	*x = ListWorkersResponse{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkersResponse) ProtoMessage() {}

func (x *ListWorkersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkersResponse.ProtoReflect.Descriptor instead.
func (*ListWorkersResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{20}
}

func (x *ListWorkersResponse) GetWorkers() []*WorkerInfo {
	if x != nil {
		return x.Workers
	}
	return nil
}

// Worker information
type WorkerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	MaxVus        int32                  `protobuf:"varint,3,opt,name=max_vus,json=maxVus,proto3" json:"max_vus,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	LastSeenMs    int64                  `protobuf:"varint,5,opt,name=last_seen_ms,json=lastSeenMs,proto3" json:"last_seen_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerInfo) Reset() {
	*x = WorkerInfo{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerInfo) ProtoMessage() {}

func (x *WorkerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerInfo.ProtoReflect.Descriptor instead.
func (*WorkerInfo) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{21}
}

func (x *WorkerInfo) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WorkerInfo) GetMaxVus() int32 {
	if x != nil {
		return x.MaxVus
	}
	return 0
}

func (x *WorkerInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkerInfo) GetLastSeenMs() int64 {
	if x != nil {
		return x.LastSeenMs
	}
	return 0
}

var File_proto_orchestrator_orchestrator_proto protoreflect.FileDescriptor

const file_proto_orchestrator_orchestrator_proto_rawDesc = "" +
	"\n" +
	"%proto/orchestrator/orchestrator.proto\x12\forchestrator\x1a\x1bproto/metrics/metrics.proto\"\xbc\x02\n" +
	"\bTestPlan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12+\n" +
	"\x06stages\x18\x03 \x03(\v2\x13.orchestrator.StageR\x06stages\x12,\n" +
	"\x04http\x18\x04 \x01(\v2\x18.orchestrator.HTTPConfigR\x04http\x12C\n" +
	"\tvariables\x18\x05 \x03(\v2%.orchestrator.TestPlan.VariablesEntryR\tvariables\x12.\n" +
	"\x13total_virtual_users\x18\x06 \x01(\x05R\x11totalVirtualUsers\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"[\n" +
	"\x05Stage\x12\x1a\n" +
	"\bduration\x18\x01 \x01(\tR\bduration\x12\x1d\n" +
	"\n" +
	"target_vus\x18\x02 \x01(\x05R\ttargetVus\x12\x17\n" +
	"\aramp_up\x18\x03 \x01(\tR\x06rampUp\"\xf6\x01\n" +
	"\n" +
	"HTTPConfig\x12\x19\n" +
	"\bbase_url\x18\x01 \x01(\tR\abaseUrl\x121\n" +
	"\brequests\x18\x02 \x03(\v2\x15.orchestrator.RequestR\brequests\x12?\n" +
	"\aheaders\x18\x03 \x03(\v2%.orchestrator.HTTPConfig.HeadersEntryR\aheaders\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x05R\ttimeoutMs\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa0\x02\n" +
	"\aRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12<\n" +
	"\aheaders\x18\x03 \x03(\v2\".orchestrator.Request.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x127\n" +
	"\n" +
	"assertions\x18\x05 \x03(\v2\x17.orchestrator.AssertionR\n" +
	"assertions\x12\"\n" +
	"\rthink_time_ms\x18\x06 \x01(\x05R\vthinkTimeMs\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf6\x01\n" +
	"\tAssertion\x12D\n" +
	"\vstatus_code\x18\x01 \x01(\v2!.orchestrator.StatusCodeAssertionH\x00R\n" +
	"statusCode\x12J\n" +
	"\rresponse_time\x18\x02 \x01(\v2#.orchestrator.ResponseTimeAssertionH\x00R\fresponseTime\x12J\n" +
	"\rbody_contains\x18\x03 \x01(\v2#.orchestrator.BodyContainsAssertionH\x00R\fbodyContainsB\v\n" +
	"\tassertion\"1\n" +
	"\x13StatusCodeAssertion\x12\x1a\n" +
	"\bexpected\x18\x01 \x01(\x05R\bexpected\"N\n" +
	"\x15ResponseTimeAssertion\x12\x1e\n" +
	"\n" +
	"percentile\x18\x01 \x01(\tR\n" +
	"percentile\x12\x15\n" +
	"\x06max_ms\x18\x02 \x01(\x05R\x05maxMs\"5\n" +
	"\x15BodyContainsAssertion\x12\x1c\n" +
	"\tsubstring\x18\x01 \x01(\tR\tsubstring\"?\n" +
	"\x11DistributeRequest\x12*\n" +
	"\x04plan\x18\x01 \x01(\v2\x16.orchestrator.TestPlanR\x04plan\"\x93\x02\n" +
	"\x12DistributeResponse\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12)\n" +
	"\x10workers_assigned\x18\x02 \x01(\x05R\x0fworkersAssigned\x12p\n" +
	"\x16worker_vu_distribution\x18\x03 \x03(\v2:.orchestrator.DistributeResponse.WorkerVuDistributionEntryR\x14workerVuDistribution\x1aG\n" +
	"\x19WorkerVuDistributionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"/\n" +
	"\x14StreamMetricsRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\"o\n" +
	"\x15StreamMetricsResponse\x123\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x17.metrics.MetricSnapshotR\bsnapshot\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\"\xf3\x01\n" +
	"\x15RegisterWorkerRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x17\n" +
	"\amax_vus\x18\x03 \x01(\x05R\x06maxVus\x12M\n" +
	"\bmetadata\x18\x04 \x03(\v21.orchestrator.RegisterWorkerRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"L\n" +
	"\x16RegisterWorkerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x11TestStatusRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\"\xb4\x02\n" +
	"\x12TestStatusResponse\x12?\n" +
	"\x06status\x18\x01 \x01(\x0e2'.orchestrator.TestStatusResponse.StatusR\x06status\x12%\n" +
	"\x0eactive_workers\x18\x02 \x01(\x05R\ractiveWorkers\x12\x1b\n" +
	"\ttotal_vus\x18\x03 \x01(\x05R\btotalVus\x12@\n" +
	"\x0fcurrent_metrics\x18\x04 \x01(\v2\x17.metrics.MetricSnapshotR\x0ecurrentMetrics\"W\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\x12\v\n" +
	"\aSTOPPED\x10\x05\"*\n" +
	"\x0fStopTestRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\"F\n" +
	"\x10StopTestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"3\n" +
	"\x15ReportMetricsResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\x14\n" +
	"\x12ListWorkersRequest\"I\n" +
	"\x13ListWorkersResponse\x122\n" +
	"\aworkers\x18\x01 \x03(\v2\x18.orchestrator.WorkerInfoR\aworkers\"\x96\x01\n" +
	"\n" +
	"WorkerInfo\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x17\n" +
	"\amax_vus\x18\x03 \x01(\x05R\x06maxVus\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12 \n" +
	"\flast_seen_ms\x18\x05 \x01(\x03R\n" +
	"lastSeenMs2\xe6\x04\n" +
	"\x13OrchestratorService\x12W\n" +
	"\x12DistributeTestPlan\x12\x1f.orchestrator.DistributeRequest\x1a .orchestrator.DistributeResponse\x12Z\n" +
	"\rStreamMetrics\x12\".orchestrator.StreamMetricsRequest\x1a#.orchestrator.StreamMetricsResponse0\x01\x12[\n" +
	"\x0eRegisterWorker\x12#.orchestrator.RegisterWorkerRequest\x1a$.orchestrator.RegisterWorkerResponse\x12R\n" +
	"\rGetTestStatus\x12\x1f.orchestrator.TestStatusRequest\x1a .orchestrator.TestStatusResponse\x12I\n" +
	"\bStopTest\x12\x1d.orchestrator.StopTestRequest\x1a\x1e.orchestrator.StopTestResponse\x12J\n" +
	"\rReportMetrics\x12\x14.metrics.MetricBatch\x1a#.orchestrator.ReportMetricsResponse\x12R\n" +
	"\vListWorkers\x12 .orchestrator.ListWorkersRequest\x1a!.orchestrator.ListWorkersResponseB;Z9github.com/vermakmanish001/go_sentinel/proto/orchestratorb\x06proto3"

var (
	file_proto_orchestrator_orchestrator_proto_rawDescOnce sync.Once
	file_proto_orchestrator_orchestrator_proto_rawDescData []byte
)

func file_proto_orchestrator_orchestrator_proto_rawDescGZIP() []byte {
	file_proto_orchestrator_orchestrator_proto_rawDescOnce.Do(func() {
		file_proto_orchestrator_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_orchestrator_orchestrator_proto_rawDesc), len(file_proto_orchestrator_orchestrator_proto_rawDesc)))
	})
	return file_proto_orchestrator_orchestrator_proto_rawDescData
}

var file_proto_orchestrator_orchestrator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_orchestrator_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_proto_orchestrator_orchestrator_proto_goTypes = []any{
	(TestStatusResponse_Status)(0), // 0: orchestrator.TestStatusResponse.Status
	(*TestPlan)(nil),               // 1: orchestrator.TestPlan
	(*Stage)(nil),                  // 2: orchestrator.Stage
	(*HTTPConfig)(nil),             // 3: orchestrator.HTTPConfig
	(*Request)(nil),                // 4: orchestrator.Request
	(*Assertion)(nil),              // 5: orchestrator.Assertion
	(*StatusCodeAssertion)(nil),    // 6: orchestrator.StatusCodeAssertion
	(*ResponseTimeAssertion)(nil),  // 7: orchestrator.ResponseTimeAssertion
	(*BodyContainsAssertion)(nil),  // 8: orchestrator.BodyContainsAssertion
	(*DistributeRequest)(nil),      // 9: orchestrator.DistributeRequest
	(*DistributeResponse)(nil),     // 10: orchestrator.DistributeResponse
	(*StreamMetricsRequest)(nil),   // 11: orchestrator.StreamMetricsRequest
	(*StreamMetricsResponse)(nil),  // 12: orchestrator.StreamMetricsResponse
	(*RegisterWorkerRequest)(nil),  // 13: orchestrator.RegisterWorkerRequest
	(*RegisterWorkerResponse)(nil), // 14: orchestrator.RegisterWorkerResponse
	(*TestStatusRequest)(nil),      // 15: orchestrator.TestStatusRequest
	(*TestStatusResponse)(nil),     // 16: orchestrator.TestStatusResponse
	(*StopTestRequest)(nil),        // 17: orchestrator.StopTestRequest
	(*StopTestResponse)(nil),       // 18: orchestrator.StopTestResponse
	(*ReportMetricsResponse)(nil),  // 19: orchestrator.ReportMetricsResponse
	(*ListWorkersRequest)(nil),     // 20: orchestrator.ListWorkersRequest
	(*ListWorkersResponse)(nil),    // 21: orchestrator.ListWorkersResponse
	(*WorkerInfo)(nil),             // 22: orchestrator.WorkerInfo
	nil,                            // 23: orchestrator.TestPlan.VariablesEntry
	nil,                            // 24: orchestrator.HTTPConfig.HeadersEntry
	nil,                            // 25: orchestrator.Request.HeadersEntry
	nil,                            // 26: orchestrator.DistributeResponse.WorkerVuDistributionEntry
	nil,                            // 27: orchestrator.RegisterWorkerRequest.MetadataEntry
	(*metrics.MetricSnapshot)(nil), // 28: metrics.MetricSnapshot
	(*metrics.MetricBatch)(nil),    // 29: metrics.MetricBatch
}
var file_proto_orchestrator_orchestrator_proto_depIdxs = []int32{
	2,  // 0: orchestrator.TestPlan.stages:type_name -> orchestrator.Stage
	3,  // 1: orchestrator.TestPlan.http:type_name -> orchestrator.HTTPConfig
	23, // 2: orchestrator.TestPlan.variables:type_name -> orchestrator.TestPlan.VariablesEntry
	4,  // 3: orchestrator.HTTPConfig.requests:type_name -> orchestrator.Request
	24, // 4: orchestrator.HTTPConfig.headers:type_name -> orchestrator.HTTPConfig.HeadersEntry
	25, // 5: orchestrator.Request.headers:type_name -> orchestrator.Request.HeadersEntry
	5,  // 6: orchestrator.Request.assertions:type_name -> orchestrator.Assertion
	6,  // 7: orchestrator.Assertion.status_code:type_name -> orchestrator.StatusCodeAssertion
	7,  // 8: orchestrator.Assertion.response_time:type_name -> orchestrator.ResponseTimeAssertion
	8,  // 9: orchestrator.Assertion.body_contains:type_name -> orchestrator.BodyContainsAssertion
	1,  // 10: orchestrator.DistributeRequest.plan:type_name -> orchestrator.TestPlan
	26, // 11: orchestrator.DistributeResponse.worker_vu_distribution:type_name -> orchestrator.DistributeResponse.WorkerVuDistributionEntry
	28, // 12: orchestrator.StreamMetricsResponse.snapshot:type_name -> metrics.MetricSnapshot
	27, // 13: orchestrator.RegisterWorkerRequest.metadata:type_name -> orchestrator.RegisterWorkerRequest.MetadataEntry
	0,  // 14: orchestrator.TestStatusResponse.status:type_name -> orchestrator.TestStatusResponse.Status
	28, // 15: orchestrator.TestStatusResponse.current_metrics:type_name -> metrics.MetricSnapshot
	22, // 16: orchestrator.ListWorkersResponse.workers:type_name -> orchestrator.WorkerInfo
	9,  // 17: orchestrator.OrchestratorService.DistributeTestPlan:input_type -> orchestrator.DistributeRequest
	11, // 18: orchestrator.OrchestratorService.StreamMetrics:input_type -> orchestrator.StreamMetricsRequest
	13, // 19: orchestrator.OrchestratorService.RegisterWorker:input_type -> orchestrator.RegisterWorkerRequest
	15, // 20: orchestrator.OrchestratorService.GetTestStatus:input_type -> orchestrator.TestStatusRequest
	17, // 21: orchestrator.OrchestratorService.StopTest:input_type -> orchestrator.StopTestRequest
	29, // 22: orchestrator.OrchestratorService.ReportMetrics:input_type -> metrics.MetricBatch
	20, // 23: orchestrator.OrchestratorService.ListWorkers:input_type -> orchestrator.ListWorkersRequest
	10, // 24: orchestrator.OrchestratorService.DistributeTestPlan:output_type -> orchestrator.DistributeResponse
	12, // 25: orchestrator.OrchestratorService.StreamMetrics:output_type -> orchestrator.StreamMetricsResponse
	14, // 26: orchestrator.OrchestratorService.RegisterWorker:output_type -> orchestrator.RegisterWorkerResponse
	16, // 27: orchestrator.OrchestratorService.GetTestStatus:output_type -> orchestrator.TestStatusResponse
	18, // 28: orchestrator.OrchestratorService.StopTest:output_type -> orchestrator.StopTestResponse
	19, // 29: orchestrator.OrchestratorService.ReportMetrics:output_type -> orchestrator.ReportMetricsResponse
	21, // 30: orchestrator.OrchestratorService.ListWorkers:output_type -> orchestrator.ListWorkersResponse
	24, // [24:31] is the sub-list for method output_type
	17, // [17:24] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_orchestrator_orchestrator_proto_init() }
func file_proto_orchestrator_orchestrator_proto_init() {
	if File_proto_orchestrator_orchestrator_proto != nil {
		return
	}
	file_proto_orchestrator_orchestrator_proto_msgTypes[4].OneofWrappers = []any{
		(*Assertion_StatusCode)(nil),
		(*Assertion_ResponseTime)(nil),
		(*Assertion_BodyContains)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_orchestrator_orchestrator_proto_rawDesc), len(file_proto_orchestrator_orchestrator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_orchestrator_orchestrator_proto_goTypes,
		DependencyIndexes: file_proto_orchestrator_orchestrator_proto_depIdxs,
		EnumInfos:         file_proto_orchestrator_orchestrator_proto_enumTypes,
		MessageInfos:      file_proto_orchestrator_orchestrator_proto_msgTypes,
	}.Build()
	File_proto_orchestrator_orchestrator_proto = out.File
	file_proto_orchestrator_orchestrator_proto_goTypes = nil
	file_proto_orchestrator_orchestrator_proto_depIdxs = nil
}
