// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/orchestrator/orchestrator.proto

package orchestrator

import (
	context "context"
	metrics "github.com/vermakmanish001/go_sentinel/proto/metrics"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrchestratorService_DistributeTestPlan_FullMethodName = "/orchestrator.OrchestratorService/DistributeTestPlan"
	OrchestratorService_StreamMetrics_FullMethodName      = "/orchestrator.OrchestratorService/StreamMetrics"
	OrchestratorService_RegisterWorker_FullMethodName     = "/orchestrator.OrchestratorService/RegisterWorker"
	OrchestratorService_GetTestStatus_FullMethodName      = "/orchestrator.OrchestratorService/GetTestStatus"
	OrchestratorService_StopTest_FullMethodName           = "/orchestrator.OrchestratorService/StopTest"
	OrchestratorService_ReportMetrics_FullMethodName      = "/orchestrator.OrchestratorService/ReportMetrics"
	OrchestratorService_ListWorkers_FullMethodName        = "/orchestrator.OrchestratorService/ListWorkers"
)

// OrchestratorServiceClient is the client API for OrchestratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Orchestrator service for managing distributed load tests
type OrchestratorServiceClient interface {
	// Submit a test plan to be distributed across workers
	DistributeTestPlan(ctx context.Context, in *DistributeRequest, opts ...grpc.CallOption) (*DistributeResponse, error)
	// Stream aggregated metrics from all workers
	StreamMetrics(ctx context.Context, in *StreamMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamMetricsResponse], error)
	// Register a worker node
	RegisterWorker(ctx context.Context, in *RegisterWorkerRequest, opts ...grpc.CallOption) (*RegisterWorkerResponse, error)
	// Get current test status
	GetTestStatus(ctx context.Context, in *TestStatusRequest, opts ...grpc.CallOption) (*TestStatusResponse, error)
	// Stop a running test
	StopTest(ctx context.Context, in *StopTestRequest, opts ...grpc.CallOption) (*StopTestResponse, error)
	// Report metrics from a worker
	ReportMetrics(ctx context.Context, in *metrics.MetricBatch, opts ...grpc.CallOption) (*ReportMetricsResponse, error)
	// List registered workers
	ListWorkers(ctx context.Context, in *ListWorkersRequest, opts ...grpc.CallOption) (*ListWorkersResponse, error)
}

type orchestratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorServiceClient(cc grpc.ClientConnInterface) OrchestratorServiceClient {
	return &orchestratorServiceClient{cc}
}

func (c *orchestratorServiceClient) DistributeTestPlan(ctx context.Context, in *DistributeRequest, opts ...grpc.CallOption) (*DistributeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DistributeResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_DistributeTestPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) StreamMetrics(ctx context.Context, in *StreamMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamMetricsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrchestratorService_ServiceDesc.Streams[0], OrchestratorService_StreamMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamMetricsRequest, StreamMetricsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrchestratorService_StreamMetricsClient = grpc.ServerStreamingClient[StreamMetricsResponse]

func (c *orchestratorServiceClient) RegisterWorker(ctx context.Context, in *RegisterWorkerRequest, opts ...grpc.CallOption) (*RegisterWorkerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterWorkerResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_RegisterWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) GetTestStatus(ctx context.Context, in *TestStatusRequest, opts ...grpc.CallOption) (*TestStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestStatusResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_GetTestStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) StopTest(ctx context.Context, in *StopTestRequest, opts ...grpc.CallOption) (*StopTestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopTestResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_StopTest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) ReportMetrics(ctx context.Context, in *metrics.MetricBatch, opts ...grpc.CallOption) (*ReportMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportMetricsResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_ReportMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) ListWorkers(ctx context.Context, in *ListWorkersRequest, opts ...grpc.CallOption) (*ListWorkersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkersResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_ListWorkers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorServiceServer is the server API for OrchestratorService service.
// All implementations must embed UnimplementedOrchestratorServiceServer
// for forward compatibility.
//
// Orchestrator service for managing distributed load tests
type OrchestratorServiceServer interface {
	// Submit a test plan to be distributed across workers
	DistributeTestPlan(context.Context, *DistributeRequest) (*DistributeResponse, error)
	// Stream aggregated metrics from all workers
	StreamMetrics(*StreamMetricsRequest, grpc.ServerStreamingServer[StreamMetricsResponse]) error
	// Register a worker node
	RegisterWorker(context.Context, *RegisterWorkerRequest) (*RegisterWorkerResponse, error)
	// Get current test status
	GetTestStatus(context.Context, *TestStatusRequest) (*TestStatusResponse, error)
	// Stop a running test
	StopTest(context.Context, *StopTestRequest) (*StopTestResponse, error)
	// Report metrics from a worker
	ReportMetrics(context.Context, *metrics.MetricBatch) (*ReportMetricsResponse, error)
	// List registered workers
	ListWorkers(context.Context, *ListWorkersRequest) (*ListWorkersResponse, error)
	mustEmbedUnimplementedOrchestratorServiceServer()
}

// UnimplementedOrchestratorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestratorServiceServer struct{}

func (UnimplementedOrchestratorServiceServer) DistributeTestPlan(context.Context, *DistributeRequest) (*DistributeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DistributeTestPlan not implemented")
}
func (UnimplementedOrchestratorServiceServer) StreamMetrics(*StreamMetricsRequest, grpc.ServerStreamingServer[StreamMetricsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamMetrics not implemented")
}
func (UnimplementedOrchestratorServiceServer) RegisterWorker(context.Context, *RegisterWorkerRequest) (*RegisterWorkerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterWorker not implemented")
}
func (UnimplementedOrchestratorServiceServer) GetTestStatus(context.Context, *TestStatusRequest) (*TestStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTestStatus not implemented")
}
func (UnimplementedOrchestratorServiceServer) StopTest(context.Context, *StopTestRequest) (*StopTestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopTest not implemented")
}
func (UnimplementedOrchestratorServiceServer) ReportMetrics(context.Context, *metrics.MetricBatch) (*ReportMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportMetrics not implemented")
}
func (UnimplementedOrchestratorServiceServer) ListWorkers(context.Context, *ListWorkersRequest) (*ListWorkersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkers not implemented")
}
func (UnimplementedOrchestratorServiceServer) mustEmbedUnimplementedOrchestratorServiceServer() {}
func (UnimplementedOrchestratorServiceServer) testEmbeddedByValue()                             {}

// UnsafeOrchestratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorServiceServer will
// result in compilation errors.
type UnsafeOrchestratorServiceServer interface {
	mustEmbedUnimplementedOrchestratorServiceServer()
}

func RegisterOrchestratorServiceServer(s grpc.ServiceRegistrar, srv OrchestratorServiceServer) {
	// If the following call panics, it indicates UnimplementedOrchestratorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrchestratorService_ServiceDesc, srv)
}

func _OrchestratorService_DistributeTestPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DistributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).DistributeTestPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_DistributeTestPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).DistributeTestPlan(ctx, req.(*DistributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_StreamMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrchestratorServiceServer).StreamMetrics(m, &grpc.GenericServerStream[StreamMetricsRequest, StreamMetricsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrchestratorService_StreamMetricsServer = grpc.ServerStreamingServer[StreamMetricsResponse]

func _OrchestratorService_RegisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).RegisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_RegisterWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).RegisterWorker(ctx, req.(*RegisterWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_GetTestStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).GetTestStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_GetTestStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).GetTestStatus(ctx, req.(*TestStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_StopTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopTestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).StopTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_StopTest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).StopTest(ctx, req.(*StopTestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_ReportMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(metrics.MetricBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).ReportMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_ReportMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).ReportMetrics(ctx, req.(*metrics.MetricBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_ListWorkers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).ListWorkers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_ListWorkers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).ListWorkers(ctx, req.(*ListWorkersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrchestratorService_ServiceDesc is the grpc.ServiceDesc for OrchestratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchestratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orchestrator.OrchestratorService",
	HandlerType: (*OrchestratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DistributeTestPlan",
			Handler:    _OrchestratorService_DistributeTestPlan_Handler,
		},
		{
			MethodName: "RegisterWorker",
			Handler:    _OrchestratorService_RegisterWorker_Handler,
		},
		{
			MethodName: "GetTestStatus",
			Handler:    _OrchestratorService_GetTestStatus_Handler,
		},
		{
			MethodName: "StopTest",
			Handler:    _OrchestratorService_StopTest_Handler,
		},
		{
			MethodName: "ReportMetrics",
			Handler:    _OrchestratorService_ReportMetrics_Handler,
		},
		{
			MethodName: "ListWorkers",
			Handler:    _OrchestratorService_ListWorkers_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMetrics",
			Handler:       _OrchestratorService_StreamMetrics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/orchestrator/orchestrator.proto",
}
