// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/metrics/metrics.proto

package metrics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Metric snapshot containing aggregated metrics
type MetricSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rps           *RPSSnapshot           `protobuf:"bytes,1,opt,name=rps,proto3" json:"rps,omitempty"`
	Latency       *LatencyHistogram      `protobuf:"bytes,2,opt,name=latency,proto3" json:"latency,omitempty"`
	ErrorRate     *ErrorRate             `protobuf:"bytes,3,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	TotalRequests int64                  `protobuf:"varint,4,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	TotalErrors   int64                  `protobuf:"varint,5,opt,name=total_errors,json=totalErrors,proto3" json:"total_errors,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,6,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	WorkerId      string                 `protobuf:"bytes,7,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"` // empty for aggregated metrics
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricSnapshot) Reset() {
	*x = MetricSnapshot{}
	mi := &file_proto_metrics_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricSnapshot) ProtoMessage() {}

func (x *MetricSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricSnapshot.ProtoReflect.Descriptor instead.
func (*MetricSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_metrics_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *MetricSnapshot) GetRps() *RPSSnapshot {
	if x != nil {
		return x.Rps
	}
	return nil
}

func (x *MetricSnapshot) GetLatency() *LatencyHistogram {
	if x != nil {
		return x.Latency
	}
	return nil
}

func (x *MetricSnapshot) GetErrorRate() *ErrorRate {
	if x != nil {
		return x.ErrorRate
	}
	return nil
}

func (x *MetricSnapshot) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *MetricSnapshot) GetTotalErrors() int64 {
	if x != nil {
		return x.TotalErrors
	}
	return 0
}

func (x *MetricSnapshot) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *MetricSnapshot) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

// Requests per second snapshot
type RPSSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Current       float64                `protobuf:"fixed64,1,opt,name=current,proto3" json:"current,omitempty"`
	Average       float64                `protobuf:"fixed64,2,opt,name=average,proto3" json:"average,omitempty"`
	Peak          float64                `protobuf:"fixed64,3,opt,name=peak,proto3" json:"peak,omitempty"`
	WindowSeconds int64                  `protobuf:"varint,4,opt,name=window_seconds,json=windowSeconds,proto3" json:"window_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPSSnapshot) Reset() {
	*x = RPSSnapshot{}
	mi := &file_proto_metrics_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPSSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPSSnapshot) ProtoMessage() {}

func (x *RPSSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPSSnapshot.ProtoReflect.Descriptor instead.
func (*RPSSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_metrics_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *RPSSnapshot) GetCurrent() float64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *RPSSnapshot) GetAverage() float64 {
	if x != nil {
		return x.Average
	}
	return 0
}

func (x *RPSSnapshot) GetPeak() float64 {
	if x != nil {
		return x.Peak
	}
	return 0
}

func (x *RPSSnapshot) GetWindowSeconds() int64 {
	if x != nil {
		return x.WindowSeconds
	}
	return 0
}

// Latency histogram with percentiles
type LatencyHistogram struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinMs         int64                  `protobuf:"varint,1,opt,name=min_ms,json=minMs,proto3" json:"min_ms,omitempty"`
	MaxMs         int64                  `protobuf:"varint,2,opt,name=max_ms,json=maxMs,proto3" json:"max_ms,omitempty"`
	MeanMs        int64                  `protobuf:"varint,3,opt,name=mean_ms,json=meanMs,proto3" json:"mean_ms,omitempty"`
	P50Ms         int64                  `protobuf:"varint,4,opt,name=p50_ms,json=p50Ms,proto3" json:"p50_ms,omitempty"`
	P95Ms         int64                  `protobuf:"varint,5,opt,name=p95_ms,json=p95Ms,proto3" json:"p95_ms,omitempty"`
	P99Ms         int64                  `protobuf:"varint,6,opt,name=p99_ms,json=p99Ms,proto3" json:"p99_ms,omitempty"`
	P999Ms        int64                  `protobuf:"varint,7,opt,name=p999_ms,json=p999Ms,proto3" json:"p999_ms,omitempty"`
	Count         int64                  `protobuf:"varint,8,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatencyHistogram) Reset() {
	*x = LatencyHistogram{}
	mi := &file_proto_metrics_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatencyHistogram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatencyHistogram) ProtoMessage() {}

func (x *LatencyHistogram) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatencyHistogram.ProtoReflect.Descriptor instead.
func (*LatencyHistogram) Descriptor() ([]byte, []int) {
	return file_proto_metrics_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *LatencyHistogram) GetMinMs() int64 {
	if x != nil {
		return x.MinMs
	}
	return 0
}

func (x *LatencyHistogram) GetMaxMs() int64 {
	if x != nil {
		return x.MaxMs
	}
	return 0
}

func (x *LatencyHistogram) GetMeanMs() int64 {
	if x != nil {
		return x.MeanMs
	}
	return 0
}

func (x *LatencyHistogram) GetP50Ms() int64 {
	if x != nil {
		return x.P50Ms
	}
	return 0
}

func (x *LatencyHistogram) GetP95Ms() int64 {
	if x != nil {
		return x.P95Ms
	}
	return 0
}

func (x *LatencyHistogram) GetP99Ms() int64 {
	if x != nil {
		return x.P99Ms
	}
	return 0
}

func (x *LatencyHistogram) GetP999Ms() int64 {
	if x != nil {
		return x.P999Ms
	}
	return 0
}

func (x *LatencyHistogram) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Error rate metrics
type ErrorRate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Rate             float64                `protobuf:"fixed64,1,opt,name=rate,proto3" json:"rate,omitempty"`                                                                                                                             // errors per second
	Percentage       float64                `protobuf:"fixed64,2,opt,name=percentage,proto3" json:"percentage,omitempty"`                                                                                                                 // error percentage
	StatusCodeCounts map[int32]int64        `protobuf:"bytes,3,rep,name=status_code_counts,json=statusCodeCounts,proto3" json:"status_code_counts,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // status code -> count
	ErrorMessages    []string               `protobuf:"bytes,4,rep,name=error_messages,json=errorMessages,proto3" json:"error_messages,omitempty"`                                                                                        // sample error messages
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ErrorRate) Reset() {
	*x = ErrorRate{}
	mi := &file_proto_metrics_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorRate) ProtoMessage() {}

func (x *ErrorRate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorRate.ProtoReflect.Descriptor instead.
func (*ErrorRate) Descriptor() ([]byte, []int) {
	return file_proto_metrics_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorRate) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *ErrorRate) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *ErrorRate) GetStatusCodeCounts() map[int32]int64 {
	if x != nil {
		return x.StatusCodeCounts
	}
	return nil
}

func (x *ErrorRate) GetErrorMessages() []string {
	if x != nil {
		return x.ErrorMessages
	}
	return nil
}

// Individual metric point
type MetricPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricPoint) Reset() {
	*x = MetricPoint{}
	mi := &file_proto_metrics_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricPoint) ProtoMessage() {}

func (x *MetricPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricPoint.ProtoReflect.Descriptor instead.
func (*MetricPoint) Descriptor() ([]byte, []int) {
	return file_proto_metrics_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *MetricPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricPoint) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *MetricPoint) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// Metric batch from a worker
type MetricBatch struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WorkerId         string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Points           []*MetricPoint         `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	LatencyHistogram *LatencyHistogram      `protobuf:"bytes,3,opt,name=latency_histogram,json=latencyHistogram,proto3" json:"latency_histogram,omitempty"`
	RpsSnapshot      *RPSSnapshot           `protobuf:"bytes,4,opt,name=rps_snapshot,json=rpsSnapshot,proto3" json:"rps_snapshot,omitempty"`
	ErrorRate        *ErrorRate             `protobuf:"bytes,5,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	BatchTimestampMs int64                  `protobuf:"varint,6,opt,name=batch_timestamp_ms,json=batchTimestampMs,proto3" json:"batch_timestamp_ms,omitempty"`
	TotalRequests    int64                  `protobuf:"varint,7,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	TotalErrors      int64                  `protobuf:"varint,8,opt,name=total_errors,json=totalErrors,proto3" json:"total_errors,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MetricBatch) Reset() {
	*x = MetricBatch{}
	mi := &file_proto_metrics_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricBatch) ProtoMessage() {}

func (x *MetricBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricBatch.ProtoReflect.Descriptor instead.
func (*MetricBatch) Descriptor() ([]byte, []int) {
	return file_proto_metrics_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *MetricBatch) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *MetricBatch) GetPoints() []*MetricPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *MetricBatch) GetLatencyHistogram() *LatencyHistogram {
	if x != nil {
		return x.LatencyHistogram
	}
	return nil
}

func (x *MetricBatch) GetRpsSnapshot() *RPSSnapshot {
	if x != nil {
		return x.RpsSnapshot
	}
	return nil
}

func (x *MetricBatch) GetErrorRate() *ErrorRate {
	if x != nil {
		return x.ErrorRate
	}
	return nil
}

func (x *MetricBatch) GetBatchTimestampMs() int64 {
	if x != nil {
		return x.BatchTimestampMs
	}
	return 0
}

func (x *MetricBatch) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *MetricBatch) GetTotalErrors() int64 {
	if x != nil {
		return x.TotalErrors
	}
	return 0
}

var File_proto_metrics_metrics_proto protoreflect.FileDescriptor

const file_proto_metrics_metrics_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/metrics/metrics.proto\x12\ametrics\"\xaa\x02\n" +
	"\x0eMetricSnapshot\x12&\n" +
	"\x03rps\x18\x01 \x01(\v2\x14.metrics.RPSSnapshotR\x03rps\x123\n" +
	"\alatency\x18\x02 \x01(\v2\x19.metrics.LatencyHistogramR\alatency\x121\n" +
	"\n" +
	"error_rate\x18\x03 \x01(\v2\x12.metrics.ErrorRateR\terrorRate\x12%\n" +
	"\x0etotal_requests\x18\x04 \x01(\x03R\rtotalRequests\x12!\n" +
	"\ftotal_errors\x18\x05 \x01(\x03R\vtotalErrors\x12!\n" +
	"\ftimestamp_ms\x18\x06 \x01(\x03R\vtimestampMs\x12\x1b\n" +
	"\tworker_id\x18\a \x01(\tR\bworkerId\"|\n" +
	"\vRPSSnapshot\x12\x18\n" +
	"\acurrent\x18\x01 \x01(\x01R\acurrent\x12\x18\n" +
	"\aaverage\x18\x02 \x01(\x01R\aaverage\x12\x12\n" +
	"\x04peak\x18\x03 \x01(\x01R\x04peak\x12%\n" +
	"\x0ewindow_seconds\x18\x04 \x01(\x03R\rwindowSeconds\"\xcd\x01\n" +
	"\x10LatencyHistogram\x12\x15\n" +
	"\x06min_ms\x18\x01 \x01(\x03R\x05minMs\x12\x15\n" +
	"\x06max_ms\x18\x02 \x01(\x03R\x05maxMs\x12\x17\n" +
	"\amean_ms\x18\x03 \x01(\x03R\x06meanMs\x12\x15\n" +
	"\x06p50_ms\x18\x04 \x01(\x03R\x05p50Ms\x12\x15\n" +
	"\x06p95_ms\x18\x05 \x01(\x03R\x05p95Ms\x12\x15\n" +
	"\x06p99_ms\x18\x06 \x01(\x03R\x05p99Ms\x12\x17\n" +
	"\ap999_ms\x18\a \x01(\x03R\x06p999Ms\x12\x14\n" +
	"\x05count\x18\b \x01(\x03R\x05count\"\x83\x02\n" +
	"\tErrorRate\x12\x12\n" +
	"\x04rate\x18\x01 \x01(\x01R\x04rate\x12\x1e\n" +
	"\n" +
	"percentage\x18\x02 \x01(\x01R\n" +
	"percentage\x12V\n" +
	"\x12status_code_counts\x18\x03 \x03(\v2(.metrics.ErrorRate.StatusCodeCountsEntryR\x10statusCodeCounts\x12%\n" +
	"\x0eerror_messages\x18\x04 \x03(\tR\rerrorMessages\x1aC\n" +
	"\x15StatusCodeCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xcf\x01\n" +
	"\vMetricPoint\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\x128\n" +
	"\x06labels\x18\x04 \x03(\v2 .metrics.MetricPoint.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x03\n" +
	"\vMetricBatch\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12,\n" +
	"\x06points\x18\x02 \x03(\v2\x14.metrics.MetricPointR\x06points\x12F\n" +
	"\x11latency_histogram\x18\x03 \x01(\v2\x19.metrics.LatencyHistogramR\x10latencyHistogram\x127\n" +
	"\frps_snapshot\x18\x04 \x01(\v2\x14.metrics.RPSSnapshotR\vrpsSnapshot\x121\n" +
	"\n" +
	"error_rate\x18\x05 \x01(\v2\x12.metrics.ErrorRateR\terrorRate\x12,\n" +
	"\x12batch_timestamp_ms\x18\x06 \x01(\x03R\x10batchTimestampMs\x12%\n" +
	"\x0etotal_requests\x18\a \x01(\x03R\rtotalRequests\x12!\n" +
	"\ftotal_errors\x18\b \x01(\x03R\vtotalErrorsB6Z4github.com/vermakmanish001/go_sentinel/proto/metricsb\x06proto3"

var (
	file_proto_metrics_metrics_proto_rawDescOnce sync.Once
	file_proto_metrics_metrics_proto_rawDescData []byte
)

func file_proto_metrics_metrics_proto_rawDescGZIP() []byte {
	file_proto_metrics_metrics_proto_rawDescOnce.Do(func() {
		file_proto_metrics_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_metrics_metrics_proto_rawDesc), len(file_proto_metrics_metrics_proto_rawDesc)))
	})
	return file_proto_metrics_metrics_proto_rawDescData
}

var file_proto_metrics_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_metrics_metrics_proto_goTypes = []any{
	(*MetricSnapshot)(nil),   // 0: metrics.MetricSnapshot
	(*RPSSnapshot)(nil),      // 1: metrics.RPSSnapshot
	(*LatencyHistogram)(nil), // 2: metrics.LatencyHistogram
	(*ErrorRate)(nil),        // 3: metrics.ErrorRate
	(*MetricPoint)(nil),      // 4: metrics.MetricPoint
	(*MetricBatch)(nil),      // 5: metrics.MetricBatch
	nil,                      // 6: metrics.ErrorRate.StatusCodeCountsEntry
	nil,                      // 7: metrics.MetricPoint.LabelsEntry
}
var file_proto_metrics_metrics_proto_depIdxs = []int32{
	1, // 0: metrics.MetricSnapshot.rps:type_name -> metrics.RPSSnapshot
	2, // 1: metrics.MetricSnapshot.latency:type_name -> metrics.LatencyHistogram
	3, // 2: metrics.MetricSnapshot.error_rate:type_name -> metrics.ErrorRate
	6, // 3: metrics.ErrorRate.status_code_counts:type_name -> metrics.ErrorRate.StatusCodeCountsEntry
	7, // 4: metrics.MetricPoint.labels:type_name -> metrics.MetricPoint.LabelsEntry
	4, // 5: metrics.MetricBatch.points:type_name -> metrics.MetricPoint
	2, // 6: metrics.MetricBatch.latency_histogram:type_name -> metrics.LatencyHistogram
	1, // 7: metrics.MetricBatch.rps_snapshot:type_name -> metrics.RPSSnapshot
	3, // 8: metrics.MetricBatch.error_rate:type_name -> metrics.ErrorRate
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_proto_metrics_metrics_proto_init() }
func file_proto_metrics_metrics_proto_init() {
	if File_proto_metrics_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_metrics_metrics_proto_rawDesc), len(file_proto_metrics_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_metrics_metrics_proto_goTypes,
		DependencyIndexes: file_proto_metrics_metrics_proto_depIdxs,
		MessageInfos:      file_proto_metrics_metrics_proto_msgTypes,
	}.Build()
	File_proto_metrics_metrics_proto = out.File
	file_proto_metrics_metrics_proto_goTypes = nil
	file_proto_metrics_metrics_proto_depIdxs = nil
}
