// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/worker/worker.proto

package worker

import (
	orchestrator "github.com/vermakmanish001/go_sentinel/proto/orchestrator"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerStatus_Status int32

const (
	WorkerStatus_IDLE     WorkerStatus_Status = 0
	WorkerStatus_RUNNING  WorkerStatus_Status = 1
	WorkerStatus_STOPPING WorkerStatus_Status = 2
	WorkerStatus_ERROR    WorkerStatus_Status = 3
)

// Enum value maps for WorkerStatus_Status.
var (
	WorkerStatus_Status_name = map[int32]string{
		0: "IDLE",
		1: "RUNNING",
		2: "STOPPING",
		3: "ERROR",
	}
	WorkerStatus_Status_value = map[string]int32{
		"IDLE":     0,
		"RUNNING":  1,
		"STOPPING": 2,
		"ERROR":    3,
	}
)

func (x WorkerStatus_Status) Enum() *WorkerStatus_Status {
	p := new(WorkerStatus_Status)
	*p = x
	return p
}

func (x WorkerStatus_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkerStatus_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_worker_worker_proto_enumTypes[0].Descriptor()
}

func (WorkerStatus_Status) Type() protoreflect.EnumType {
	return &file_proto_worker_worker_proto_enumTypes[0]
}

func (x WorkerStatus_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkerStatus_Status.Descriptor instead.
func (WorkerStatus_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{2, 0}
}

// Run test request
type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	Plan          *orchestrator.TestPlan `protobuf:"bytes,2,opt,name=plan,proto3" json:"plan,omitempty"`
	AssignedVus   int32                  `protobuf:"varint,3,opt,name=assigned_vus,json=assignedVus,proto3" json:"assigned_vus,omitempty"` // number of virtual users assigned to this worker
	WorkerId      string                 `protobuf:"bytes,4,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_proto_worker_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{0}
}

func (x *RunRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *RunRequest) GetPlan() *orchestrator.TestPlan {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *RunRequest) GetAssignedVus() int32 {
	if x != nil {
		return x.AssignedVus
	}
	return 0
}

func (x *RunRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

// Run test response
type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_proto_worker_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{1}
}

func (x *RunResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RunResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Worker status
type WorkerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        WorkerStatus_Status    `protobuf:"varint,1,opt,name=status,proto3,enum=worker.WorkerStatus_Status" json:"status,omitempty"`
	CurrentTestId string                 `protobuf:"bytes,2,opt,name=current_test_id,json=currentTestId,proto3" json:"current_test_id,omitempty"`
	ActiveVus     int32                  `protobuf:"varint,3,opt,name=active_vus,json=activeVus,proto3" json:"active_vus,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerStatus) Reset() {
	*x = WorkerStatus{}
	mi := &file_proto_worker_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStatus) ProtoMessage() {}

func (x *WorkerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStatus.ProtoReflect.Descriptor instead.
func (*WorkerStatus) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerStatus) GetStatus() WorkerStatus_Status {
	if x != nil {
		return x.Status
	}
	return WorkerStatus_IDLE
}

func (x *WorkerStatus) GetCurrentTestId() string {
	if x != nil {
		return x.CurrentTestId
	}
	return ""
}

func (x *WorkerStatus) GetActiveVus() int32 {
	if x != nil {
		return x.ActiveVus
	}
	return 0
}

func (x *WorkerStatus) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *WorkerStatus) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Heartbeat request
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Status        *WorkerStatus          `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_worker_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() *WorkerStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// Heartbeat response
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_worker_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Status request
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_worker_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{5}
}

func (x *StatusRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

// Status response
type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *WorkerStatus          `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_worker_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{6}
}

func (x *StatusResponse) GetStatus() *WorkerStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// Stop request
type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_proto_worker_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{7}
}

func (x *StopRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

// Stop response
type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_proto_worker_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{8}
}

func (x *StopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_worker_worker_proto protoreflect.FileDescriptor

const file_proto_worker_worker_proto_rawDesc = "" +
	"\n" +
	"\x19proto/worker/worker.proto\x12\x06worker\x1a%proto/orchestrator/orchestrator.proto\"\x91\x01\n" +
	"\n" +
	"RunRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12*\n" +
	"\x04plan\x18\x02 \x01(\v2\x16.orchestrator.TestPlanR\x04plan\x12!\n" +
	"\fassigned_vus\x18\x03 \x01(\x05R\vassignedVus\x12\x1b\n" +
	"\tworker_id\x18\x04 \x01(\tR\bworkerId\"A\n" +
	"\vRunResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe8\x02\n" +
	"\fWorkerStatus\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.worker.WorkerStatus.StatusR\x06status\x12&\n" +
	"\x0fcurrent_test_id\x18\x02 \x01(\tR\rcurrentTestId\x12\x1d\n" +
	"\n" +
	"active_vus\x18\x03 \x01(\x05R\tactiveVus\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\x12>\n" +
	"\bmetadata\x18\x05 \x03(\v2\".worker.WorkerStatus.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\x06Status\x12\b\n" +
	"\x04IDLE\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\f\n" +
	"\bSTOPPING\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\"]\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12,\n" +
	"\x06status\x18\x02 \x01(\v2\x14.worker.WorkerStatusR\x06status\"Q\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\rStatusRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\">\n" +
	"\x0eStatusResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.worker.WorkerStatusR\x06status\"&\n" +
	"\vStopRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\"B\n" +
	"\fStopResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xf8\x01\n" +
	"\rWorkerService\x122\n" +
	"\aRunTest\x12\x12.worker.RunRequest\x1a\x13.worker.RunResponse\x12@\n" +
	"\tHeartbeat\x12\x18.worker.HeartbeatRequest\x1a\x19.worker.HeartbeatResponse\x12:\n" +
	"\tGetStatus\x12\x15.worker.StatusRequest\x1a\x16.worker.StatusResponse\x125\n" +
	"\bStopTest\x12\x13.worker.StopRequest\x1a\x14.worker.StopResponseB5Z3github.com/vermakmanish001/go_sentinel/proto/workerb\x06proto3"

var (
	file_proto_worker_worker_proto_rawDescOnce sync.Once
	file_proto_worker_worker_proto_rawDescData []byte
)

func file_proto_worker_worker_proto_rawDescGZIP() []byte {
	file_proto_worker_worker_proto_rawDescOnce.Do(func() {
		file_proto_worker_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_worker_worker_proto_rawDesc), len(file_proto_worker_worker_proto_rawDesc)))
	})
	return file_proto_worker_worker_proto_rawDescData
}

var file_proto_worker_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_worker_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_worker_worker_proto_goTypes = []any{
	(WorkerStatus_Status)(0),      // 0: worker.WorkerStatus.Status
	(*RunRequest)(nil),            // 1: worker.RunRequest
	(*RunResponse)(nil),           // 2: worker.RunResponse
	(*WorkerStatus)(nil),          // 3: worker.WorkerStatus
	(*HeartbeatRequest)(nil),      // 4: worker.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 5: worker.HeartbeatResponse
	(*StatusRequest)(nil),         // 6: worker.StatusRequest
	(*StatusResponse)(nil),        // 7: worker.StatusResponse
	(*StopRequest)(nil),           // 8: worker.StopRequest
	(*StopResponse)(nil),          // 9: worker.StopResponse
	nil,                           // 10: worker.WorkerStatus.MetadataEntry
	(*orchestrator.TestPlan)(nil), // 11: orchestrator.TestPlan
}
var file_proto_worker_worker_proto_depIdxs = []int32{
	11, // 0: worker.RunRequest.plan:type_name -> orchestrator.TestPlan
	0,  // 1: worker.WorkerStatus.status:type_name -> worker.WorkerStatus.Status
	10, // 2: worker.WorkerStatus.metadata:type_name -> worker.WorkerStatus.MetadataEntry
	3,  // 3: worker.HeartbeatRequest.status:type_name -> worker.WorkerStatus
	3,  // 4: worker.StatusResponse.status:type_name -> worker.WorkerStatus
	1,  // 5: worker.WorkerService.RunTest:input_type -> worker.RunRequest
	4,  // 6: worker.WorkerService.Heartbeat:input_type -> worker.HeartbeatRequest
	6,  // 7: worker.WorkerService.GetStatus:input_type -> worker.StatusRequest
	8,  // 8: worker.WorkerService.StopTest:input_type -> worker.StopRequest
	2,  // 9: worker.WorkerService.RunTest:output_type -> worker.RunResponse
	5,  // 10: worker.WorkerService.Heartbeat:output_type -> worker.HeartbeatResponse
	7,  // 11: worker.WorkerService.GetStatus:output_type -> worker.StatusResponse
	9,  // 12: worker.WorkerService.StopTest:output_type -> worker.StopResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_worker_worker_proto_init() }
func file_proto_worker_worker_proto_init() {
	if File_proto_worker_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_worker_worker_proto_rawDesc), len(file_proto_worker_worker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_worker_worker_proto_goTypes,
		DependencyIndexes: file_proto_worker_worker_proto_depIdxs,
		EnumInfos:         file_proto_worker_worker_proto_enumTypes,
		MessageInfos:      file_proto_worker_worker_proto_msgTypes,
	}.Build()
	File_proto_worker_worker_proto = out.File
	file_proto_worker_worker_proto_goTypes = nil
	file_proto_worker_worker_proto_depIdxs = nil
}
